#!/bin/sh

# PROVIDE: bindrev
# REQUIRE: NETWORKING ldconfig syslogd dnstap

. /etc/rc.subr

fail() { echo $@>&2; exit 1; }

if [ -f /usr/local/etc/bindrev.rc ]; then
    . /usr/local/etc/bindrev.rc
fi

test -n "$BINDREV_HOME" || fail "BINDREV_HOME not set"
test -n "$BINDREV_CONFIG" || fail "BINDREV_CONFIG not set"

export PATH=/usr/local/bin:$PATH
name="bindrev"
pidfile="/var/run/bindrev.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile $BINDREV_HOME/bin/bindrev -c $BINDREV_CONFIG"

load_rc_config $name
run_rc_command "$1"
