#!/bin/sh

# PROVIDE: bindrev
# REQUIRE: NETWORKING ldconfig syslogd dnstap

. /etc/rc.subr

load_rc_config $name

fail() { echo $@>&2; exit 1; }

test -n "$dnstap_home" || fail "dnstap_home not defined"
export PYTHONPATH=$dnstap_home/bin:$PYTHONPATH
test -n "$bindrev_home" || fail "bindrev_home not defined"
test -n "$bindrev_config" || fail "bindrev_config not defined"

name="bindrev"
pidfile="/var/run/bindrev.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile $bindrev_home/bin/bindrev -c $bindrev_config"

export PATH=/usr/local/bin:$PATH

run_rc_command "$1"
