#!/bin/sh

# PROVIDE: bindrev
# REQUIRE: NETWORKING ldconfig syslogd dnstap

. /etc/rc.subr

export PATH=/usr/local/bin:$PATH
name="bindrev"
pidfile="/var/run/bindrev.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile /home/drew/bindrev/bin/bindrev"

load_rc_config $name
run_rc_command "$1"
